kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: finance-bot-logs-pvc
  namespace: finance-bot
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: local-storage
  resources:
   requests:
     storage: 100Mi
  selector:
    matchLabels:
      type: "logs"
